name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install rename tool
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ rename
    - name: Setup JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Setup Android SDK
      uses: maxim-lobanov/setup-android-tools@v1
      with:
        packages: |
          build-tools;31.0.0
          platforms;android-31
          ndk;23.1.7779620
        cache: true
    - name: Build required modules
      run: |
        export ANDROID_SDK_ROOT=$ANDROID_HOME
        export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/23.1.7779620
        pushd app/jni
        sed -i -e 's/d+2/d+0/' boost/build-android.sh
        ./build_boost.sh
        ./build_openssl.sh
        ./build_miniupnpc.sh
        popd
    - name: Build with Gradle
      run: ./gradlew --no-daemon assembleDebug
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: android-apks
        path: app/build/outputs/apk/debug/*.apk

  build-binary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install rename tool
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ rename
    - name: Setup JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Setup Android SDK
      uses: maxim-lobanov/setup-android-tools@v1
      with:
        packages: |
          ndk;23.1.7779620
        cache: true
    - name: Build required modules
      run: |
        export ANDROID_SDK_ROOT=$ANDROID_HOME
        export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/23.1.7779620
        pushd binary/jni
        sed -i -e 's/d+2/d+0/' boost/build-android.sh
        ./build_boost.sh
        ./build_openssl.sh
        ./build_miniupnpc.sh
        popd
    - name: Build binaries with NDK
      run: |
        pushd binary/jni
        $ANDROID_NDK_HOME/ndk-build -j2 NDK_MODULE_PATH=$PWD
        popd
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: android-binaries
        path: binary/libs/*
